### PR TITLE
python file and readme

### PR DESCRIPTION
**Pull request by gabeewsuk**
Adding assignment

### CODE REVIEW

**Comment by gabeewsuk** [comment]
my assignment2

**Comment by sleddog** [comment]
Directory structure does not have your user name per requirements:
`problems/euler/num1-multof3and5-under1000/`

**Comment by DanielBachler** [comment]
The code itself looks good and solves the problem as presented.  Perhaps add in the ability to get the value to count up to from the user but that is not required by the problem.

The only issue I found was that your README was a text file and not line separated.  Just change the file to a .md file and break up the lines so that it is
Assignment2_10
 more legible!

+10

**Review by DanielBachler — APPROVED** [review]
The code itself looks good and solves the problem as presented.  Perhaps add in the ability to get the value to count up to from the user but that is not required by the problem.

The only issue I found was that your README was a text file and not line separated.  Just change the file to a .md file and break up the lines so that it is more legible!
Assignment2_10

+10

**Pull request merged**
