### PR TITLE
Solved Homework 2

### PR DESCRIPTION
**Pull request by Swingus**

### CODE REVIEW

**Comment by sleddog** [comment]
ZIP file is added as opposed to the code.  Resubmit with the individual files.
Also the directory structure is missing your username per requirements:
`problems/euler/15/java/Euler_Project_15.md`
Also title the file: README.md not Euler_Project_15.md as thats in the directory name.

**Review by lpappas98 — COMMENTED** [review]
Your code looks great! It is well commented and easy to follow. +1

**Review by Jason-Bengtson — COMMENTED** [review]
Just so you know it is in a zip file, should upload it as an actual java file for easy compilation

**Comment by Dmoayad** [comment]
The code runs perfect.



only thing I would suggest changing is the README.md to make it  easier for people who are new to java to run code.

good job +10

**Review by Dmoayad — APPROVED** [review]
code is easy to read.. nice job!
+1

**Pull request merged**
