### PR TITLE
Assignment 2 submission

### PR DESCRIPTION
**Pull request by Dmoayad**

### CODE REVIEW

**Comment by sleddog** [comment]
Minor issue - The username isn't within your directory structure per requirements:
`problems/kattis/NoDuplicates/`

**Review by cjyovich — APPROVED** [review]
Ran code as described in the README and tested one sentence without a duplicated word and one with. Runs as expected. See output below.

NoDifferenceTest

I found the output really confusing based on what the problem is solving - it is not very intuitive. I see why you did it this way given the wording of the problem, but I would expect it to output "no" when there is no duplicated word and "yes" when there is one. I had to go back and check the README to make sure it was doing what it was supposed to. I think it could be improved by adding more detailed output messages. For example, "This sentence does not contain a repeated word." and "This sentence contains a repeated word." This would eliminate any confusion on the user end. 

Otherwise, nice work! Code is readable and README is very descriptive. Extra kudos for adding the command to run in Windows because I am constantly using the wrong commands and having to look them up. +10

**Review by Swingus — APPROVED** [review]
Looks good to me +1

**Review by Dmoayad — COMMENTED** [review]
No-duplicates solution

**Pull request merged**
