### PR TITLE
Submission for assignment 2

### PR DESCRIPTION
**Pull request by ConnorLudwig**

### CODE REVIEW

**Review by Jason-Bengtson — COMMENTED** [review]
Nice job on the code, I like the way you broke your problem into many different well named methods. Also the comments were clear and easy to follow.
+1

**Comment by lpappas98** [comment]
Screen Shot 2020-03-02 at 3 19 04 PM

Your code looks nice, is well commented, but sadly it will not compile/run since you forgot to put the parenthesis after your solve() in the main method. Fix this and your code should run perfectly!

**Review by lpappas98 — CHANGES_REQUESTED** [review]
Screen Shot 2020-03-02 at 3 19 04 PM

Your code looks nice, is well commented, but sadly it will not compile/run since you forgot to put the parenthesis after your solve() in the main method. Fix this and your code should run perfectly!

**Review by ConnorLudwig — COMMENTED** [review]
I have fixed the code and the file structure and I believe this is ready to be merged.

**Review by lpappas98 — APPROVED** [review]

**Pull request merged**
